version: "3.9"

services:

  zookeeper:
    image: debezium/zookeeper:latest
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: debezium/kafka:latest
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "kdesdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    environment:
      discovery.type: single-node
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
      xpack.security.enabled: false
    ports:
      - 9200:9200
      - 9300:9300

  connect:
    image: debezium/connect:latest
    ports:
      - 8083:8083
      - 5005:5005
    links:
      - kafka
      - postgres
      - elasticsearch
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses
    depends_on:
      - zookeeper
      - kafka
      - postgres
      - elasticsearch
